// <auto-generated />
using DatabaseMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseMicroservice.Migrations
{
    [DbContext(typeof(CMSContentContext))]
    [Migration("20230330104038_users-roles-and-apikeys")]
    partial class usersrolesandapikeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabaseMicroservice.Models.TextFragment", b =>
                {
                    b.Property<string>("IdentifyingName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FragmentID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdentifyingName");

                    b.ToTable("TextFragments");
                });
#pragma warning restore 612, 618
        }
    }
}
